//
// Generated by Microsoft (R) HLSL Shader Compiler 9.26.952.2844
//
// Parameters:
//
//   sampler2D TextureSampler;
//
//
// Registers:
//
//   Name           Reg   Size
//   -------------- ----- ----
//   TextureSampler s0       1
//

    ps_3_0
    def c219, 1.8395173895e+25, 3.9938258725e+24, 4.5435787456e+30, 8.5899595863e-43 // 613
    def c0, 1, 0, -0.125, 0
    dcl_texcoord v0.xy
    dcl_texcoord9 v9
    dcl_2d s0
    mul r0, c0.xxyy, v0.xyxx
    texldl r0, r0, s0
    add r1.x, r0.w, c0.z
    cmp r1, r1.x, -c0.y, -c0.x
    texkill r1
    mov oC0, r0
    
    // LogDepth Write
    mul r19.x, v9.w, c209.x
    log r19.x, r19.x
    mul r19.x, r19.x, c209.y
    rcp r19.y, v9.w
    mul r19.y, r19.y, v9.z
    cmp oDepth, -v9_abs.y, r19.y, r19.x

// approximately 7 instruction slots used (2 texture, 5 arithmetic)
