//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
// Parameters:
//
//   float4 gShadowParam14151617;
//
//
// Registers:
//
//   Name                 Reg   Size
//   -------------------- ----- ----
//   gShadowParam14151617 c56      1
//

    ps_3_0
    def c0, 0.00999999978, 1, 0, 0
    dcl_texcoord1 v0.zw
    abs r0.x, c56.x
    cmp r0.x, -r0.x, c0.y, c0.z
    add r0.y, c0.x, -v0.z
    mul r0, r0.x, r0.y
    texkill r0
    mov oC0, v0.w

// approximately 6 instruction slots used