//
// Generated by Microsoft (R) HLSL Shader Compiler 9.26.952.2844
    vs_3_0
    def c230, 1.8395173895e+25, 3.9938258725e+24, 4.5435787456e+30, 3.4401877299e-42 // 2455
    def c0, 1, 0, 0, 0
    dcl_position v0
    dcl_texcoord v1
    dcl_normal v2
    dcl_position o0
    dcl_texcoord o1.xy
    dcl_texcoord1 o2.xy
    mad o0, v0.xyzx, c0.xxxy, c0.yyyx
    mov o1.xy, v1
    mov o2.xy, v2

// approximately 3 instruction slots used
