//
// Generated by Microsoft (R) HLSL Shader Compiler 9.26.952.2844
//
// Parameters:
//
//   sampler2D TextureSampler;
//   float4 diffuseCol;
//
//
// Registers:
//
//   Name           Reg   Size
//   -------------- ----- ----
//   diffuseCol     c66      1
//   TextureSampler s0       1
//

    ps_3_0
    def c127, 0.9999999, 1, 0, 0	// LogDepth constants
    dcl_color v0
    dcl_texcoord v1.xy
    dcl_texcoord9 v9
    dcl_2d s0
    texld r0, v1, s0
    mul r0, r0, v0
    mul oC0, r0, c66
	// ----------------------------------------------------------------- Linear2Log -----------------------------------------------------------------
	if_ne v9.y, c127.y
		rcp r20.z, c128.x
		mul r20.x, v9.w, r20.z
		mul r20.y, c128.y, r20.z
		log r20.x, r20.x
		log r20.y, r20.y
		rcp r20.y, r20.y
	else
		mov r20.x, v9.z
		rcp r20.y, v9.w
	endif
	mul oDepth, r20.x, r20.y
	// ----------------------------------------------------------------------------------------------------------------------------------------------

// approximately 3 instruction slots used (1 texture, 2 arithmetic)
