//
// Generated by Microsoft (R) HLSL Shader Compiler 9.26.952.2844
//
// Parameters:
//
//   row_major float4x4 gShadowMatrix;
//
//
// Registers:
//
//   Name          Reg   Size
//   ------------- ----- ----
//   gShadowMatrix c60      4
//

    vs_3_0
    def c230, 1.8395173895e+25, 3.9938258725e+24, 4.5435787456e+30, 3.9194318047e-42 // 2797
    def c0, 16, 8, 0, 0
    def c1, 1, 0, -1, 0
    dcl_position v0
    dcl_color v1
    dcl_texcoord v2
    dcl_position o0
    dcl_texcoord o1
    mul r0, c61, v0.y
    mad r0, v0.x, c60, r0
    mad r0, v0.z, c62, r0
    add r0, r0, c63
    min r0.z, r0.z, c1.x
    add o0.z, -r0.z, c1.x
    mad o0.xyw, r0.xyzx, c1.xxzy, c1.yyzx
    mov o1.w, r0.w
    mad o1.xy, v2, c1.xzzw, c1.yxzw
    mad o1.z, v1.x, c0.x, c0.y

// approximately 10 instruction slots used
