//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   sampler2D DiffuseTexSampler;
//   sampler2D FrameMapTexSampler;
//   float HybridAdd;
//   float gHeatHaze;
//   float gHeatPhase;
//
//
// Registers:
//
//   Name               Reg   Size
//   ------------------ ----- ----
//   HybridAdd          c64      1
//   gHeatHaze          c65      1
//   gHeatPhase         c66      1
//   DiffuseTexSampler  s0       1
//   FrameMapTexSampler s1       1
//

    ps_3_0
    def c219, 1.8395173895e+25, 3.9938258725e+24, 4.5435787456e+30, 1.1728868146e-42 // 837
    def c0, 1, 0.5, 0.159154937, 0
    def c1, 6.28318548, -3.14159274, 0, 0
    dcl_color v0
    dcl_texcoord v1.xy
    dcl_texcoord2 v2.zw
    dcl_texcoord3 v3.x
    dcl_texcoord9 v9
    dcl_2d s0
    dcl_2d s1
    mov r0.z, v2.z
    add r0.x, r0.z, v3.x
    mul r0.x, r0.x, c65.x
    mad r0.x, r0.x, c0.z, c0.y
    frc r0.x, r0.x
    mad r0.x, r0.x, c1.x, c1.y
    sincos r1.xy, r0.x
    rcp r0.x, c66.x
    mul r0.y, r0.x, r1.y
    add r0.zw, c0.x, v2
    mad r2.x, r0.z, c0.y, r0.y
    mad r0.y, r0.w, -c0.y, c0.x
    mad r2.y, r1.x, -r0.x, r0.y
    texld r0, r2, s1
    mul r0.xyz, r0, v0
    texld r1, v1, s0
    mul r0.w, r1.w, v0.w
    mul r1.xyz, r0.w, r0
    abs r2.x, c64.x
    add r2.y, c0.x, -v3.x
    mul r1.w, r0.w, r2.y
    cmp oC0, -r2.x, r0, r1
    
    // LogDepth Write
    mul r19.x, v9.w, c209.x
    log r19.x, r19.x
    mul r19.x, r19.x, c209.y
    rcp r19.y, v9.w
    mul r19.y, r19.y, v9.z
    cmp oDepth, -v9_abs.y, r19.y, r19.x

// approximately 29 instruction slots used (2 texture, 27 arithmetic)
