// Summary: removed unnecessary stipple + added linearization for HDR
// Generated by Microsoft (R) HLSL Shader Compiler 9.26.952.2844
//
// Parameters:
//
//   sampler2D StippleTexture;
//   sampler2D TextureSampler;
//   float4 globalScalars;
//
//
// Registers:
//
//   Name           Reg   Size
//   -------------- ----- ----
//   globalScalars  c39      1
//   TextureSampler s0       1
//   StippleTexture s10      1
//

    ps_3_0
    def c219, 1.8395173895e+25, 3.9938258725e+24, 4.5435787456e+30, 3.9656746540e-43 // 283
    def c0, 3.99600005, 4, 0.125, 0.25
    def c1, 0, -1, -0, 0
    def c2, 24999, 1, 2.2, 0
    dcl_texcoord v0.xy
    dcl_color v1
    dcl vPos.xy
    dcl_texcoord9 v9
    dcl_2d s0
    dcl_2d s10
    texld r0, v0, s0
    mul r0, r0, v1
    mul r0.w, r0.w, c39.x
    mul r0.xyz, r0, c39.y
    
    mov r1.x, c210.x
    cmp r1.x, -r1_abs.x, c2.y, v9.y
    if_eq -r1_abs.x, r1_abs.x
      log r0.x, r0_abs.x
      log r0.y, r0_abs.y
      log r0.z, r0_abs.z
      mul r0.xyz, r0, c2.z
      exp r0.x, r0.x
      exp r0.y, r0.y
      exp r0.z, r0.z
    endif
    
    mov oC0, r0
    
    // LogDepth Write - Void
    mul r19.x, v9.w, c209.x
    log r19.x, r19.x
    mul r19.x, r19.x, c209.y
    mul r19.z, c209.z, c209.w
    add r19.z, r19.z, -c2.x
    cmp r19.x, r19.z, c2.y, r19.x
    rcp r19.y, v9.w
    mul r19.y, r19.y, v9.z
    cmp oDepth, -v9_abs.y, r19.y, r19.x

// approximately 21 instruction slots used (3 texture, 18 arithmetic)
