//
// Generated by Microsoft (R) HLSL Shader Compiler 9.26.952.2844
//
// Parameters:
//
//   row_major float4x4 gViewInverse;
//   row_major float4x4 gWorld;
//   row_major float4x4 gWorldViewProj;
//
//
// Registers:
//
//   Name           Reg   Size
//   -------------- ----- ----
//   gWorld         c0       4
//   gWorldViewProj c8       4
//   gViewInverse   c12      4
//

    vs_3_0
    def c230, 1.8395173895e+25, 3.9938258725e+24, 4.5435787456e+30, 3.4584046100e-42 // 2468
    def c4, 9.99999975e-006, 0, 1, 0
    dcl_position v0
    dcl_color v1
    dcl_texcoord v2
    dcl_normal v3
    dcl_tangent v4
    dcl_position1 v5
    dcl_normal1 v6
    dcl_tangent1 v7
    dcl_position o0
    dcl_texcoord9 o10 // LogDepth Interpolator
    dcl_texcoord o1.xy
    dcl_texcoord1 o2
    dcl_texcoord3 o3.xyz
    dcl_texcoord4 o4.xyz
    dcl_texcoord5 o5.xyz
    dcl_color o6
    dcl_texcoord6 o7.x
    dcl_texcoord2 o8
    mov r0.xyz, v0
    add r0.xyz, r0, v5
    mul r1.xyz, r0.y, c1
    mad r1.xyz, r0.x, c0, r1
    mad r1.xyz, r0.z, c2, r1
    add r1.xyz, r1, c3
    add o3.xyz, -r1, c15
    mov o8.xyz, r1
    mov r1.xyz, v3
    add r1.xyz, r1, v6
    mul r2.xyz, r1.y, c1
    mad r1.xyw, r1.x, c0.xyzz, r2.xyzz
    mad r1.xyz, r1.z, c2, r1.xyww
    add r1.xyz, r1, c4.x
    nrm r2.xyz, r1
    mov r1, v4
    add r1, r1, v7
    mul r3.xyz, r1.y, c1
    mad r3.xyz, r1.x, c0, r3
    mad r1.xyz, r1.z, c2, r3
    add r1.xyz, r1, c4.x
    nrm r3.xyz, r1
    mul r1.xyz, r2.yzxw, r3.zxyw
    mad r1.xyz, r3.yzxw, r2.zxyw, -r1
    mov o2.xyz, r2
    mov o4.xyz, r3
    mul o5.xyz, r1.w, r1
    mul r1, r0.y, c9
    mad r1, r0.x, c8, r1
    mad r0, r0.z, c10, r1
    add r0, r0, c11
    mov o0, r0
    mov o10.zw, r0
    mov o2.w, r0.w
    mov o1.xy, v2
    mov o6, v1
    mov o7.x, c4.y
    mov o8.w, c4.z
    dp3 o10.xy, c10.xyw, c10.xyw

// approximately 41 instruction slots used
