//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float3 AzimuthColor;
//   float3 AzimuthColorEast;
//   float AzimuthHeight;
//   float AzimuthStrength;
//   float CloudBias;
//   float4 CloudColor;
//   float CloudFadeOut;
//   float CloudShadowStrength;
//   float4 CloudThicknessEdgeSmoothDetailScaleStrength;
//   float CloudThreshold;
//   sampler2D GalaxySampler;
//   float HDRExposure;
//   float3 HDRExposureClamp;
//   float HDRSunExposure;
//   sampler2D HighDetailNoiseSampler;
//   sampler2D PerlinNoiseSampler;
//   float3 SkyColor;
//   float4 StarFieldBrightness;
//   float3 SunCentre;
//   float3 SunColor;
//   float4 SunDirection;
//   float SunSize;
//   float4 SunsetColor;
//   float4 TopCloudBiasDetailThresholdHeight;
//   float3 TopCloudColor;
//
//
// Registers:
//
//   Name                                        Reg   Size
//   ------------------------------------------- ----- ----
//   SunCentre                                   c64      1
//   SunDirection                                c65      1
//   SkyColor                                    c66      1
//   AzimuthColor                                c67      1
//   SunColor                                    c68      1
//   AzimuthColorEast                            c69      1
//   AzimuthHeight                               c70      1
//   CloudColor                                  c71      1
//   SunsetColor                                 c72      1
//   CloudThreshold                              c73      1
//   CloudBias                                   c74      1
//   CloudFadeOut                                c75      1
//   TopCloudBiasDetailThresholdHeight           c76      1
//   TopCloudColor                               c77      1
//   CloudShadowStrength                         c78      1
//   AzimuthStrength                             c79      1
//   CloudThicknessEdgeSmoothDetailScaleStrength c80      1
//   StarFieldBrightness                         c81      1
//   SunSize                                     c82      1
//   HDRExposure                                 c83      1
//   HDRSunExposure                              c84      1
//   HDRExposureClamp                            c85      1
//   GalaxySampler                               s0       1
//   PerlinNoiseSampler                          s1       1
//   HighDetailNoiseSampler                      s2       1
//

    ps_3_0
    def c219, 1.8395173895e+25, 3.9938258725e+24, 4.5435787456e+30, 1.0719933252e-42 // 765
    def c0, -0.5, 0, 1, 4000
    def c1, 12.5799999, -0.0625, 0.5, 0.25
    def c2, -11.6163721, 0.9375, 0.5, 0.349999994
    def c3, 32, 0.600000024, -2, 3
    def c4, 4, 0.200000003, 0, 0
    dcl_texcoord v0.xy
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    add r0.xy, c0.x, v0
    add r0.xy, r0, r0
    dp2add r0.z, r0, r0, c0.y
    rsq r0.w, r0.z
    mul r0.xy, r0.w, r0
    rcp r0.w, r0.w
    add r0.w, -r0.w, c0.z
    mul r0.xy, r0, r0.z
    mul r1.xyz, r0.xwyw, c0.w
    nrm r0.xyz, r1
    mul_sat r0.w, r0.y, c70.x
    add r0.w, -r0.w, c0.z
    mul r0.w, r0.w, c79.x
    mad r1.x, r0.x, -c0.x, -c0.x
    mov r2.xyz, c69
    add r1.yzw, -r2.xxyz, c67.xxyz
    mad r1.xyz, r1.x, r1.yzww, c69
    mad r1.xyz, r1, r0.w, c66
    dp3 r0.x, r0, c65
    mov r2.x, c4.x
    mad_sat r0.y, r0.y, r2.x, -c75.x
    mov r2, c1
    mad r2, r0.x, r2, c2
    mov_sat r2.xyz, r2
    mul r0.x, r2.y, r2.y
    mul r0.x, r0.x, r2.y
    pow r0.z, r2.x, c3.x
    mov r0.w, c65.w
    add_sat r0.w, r0.w, c3.y
    mad r0.x, r0.x, -r0.w, r0.z
    mad r0.x, r2.z, c82.x, r0.x
    mad_sat r0.z, r2.z, c64.y, c64.x
    mul_sat r0.x, r0.x, -c0.x
    mul r0.w, r0.z, r0.z
    mad r0.z, r0.z, c3.z, c3.w
    mul r0.z, r0.z, r0.w
    mul r0.z, r0.z, c64.z
    mad r0.x, r0.x, c4.x, r0.z
    mul r2.xyz, r0.x, c68
    add_sat r3.w, -r0.x, c0.z
    mul r0.xzw, r2.xyyz, r2.xyyz
    mad r3.xyz, r0.xzww, r0.xzww, r2
    mul r3, r3, c84.x
    mul_sat r0.xzw, r1.xyyz, r3.w
    min r1.xyz, c85, r3
    add r0.xzw, r0, r1.xyyz
    texld r1, v0, s0
    mad r0.xzw, r1.xyyz, c81.y, r0
    mul r1.xy, c80.z, v0
    texld r1, r1, s2
    mul r1.x, r1.x, c80.w
    texld r3, v0, s1
    mad r1.x, r1.x, c4.y, r3.x
    mov r2.x, c73.x
    mad r1.x, r2.x, r1.x, -c74.x
    mul_sat r1.x, r1.x, c78.x
    add r1.y, -r1.x, c0.z
    add r1.xzw, -r1.x, c71.xyyz
    texld r4, v0, s2
    add r2.y, r4.x, c0.x
    mad r2.z, r2.y, c80.w, r3.x
    mad_sat r2.x, r2.x, r2.z, -c74.x
    pow r3.x, r2.x, c80.x
    mul_sat r2.x, r2.x, c80.y
    mul r2.z, r2.x, r3.x
    mad r2.x, r3.x, -r2.x, c0.z
    mul r1.y, r1.y, r2.z
    mad_sat r3.x, r2.y, c4.y, r3.z
    mul r2.y, r2.y, c80.w
    mad r2.y, r2.y, c76.y, r3.y
    mad_sat r2.y, c76.z, r2.y, -c76.x
    mul r2.y, r2.y, v0.x
    mul r2.y, r2.x, r2.y
    mad r2.x, r2.x, r2.y, r2.z
    mul r0.y, r0.y, r2.x
    mad r1.y, r1.y, r3.x, r3.x
    mul r1.y, r2.w, r1.y
    mad r1.xyz, c72, r1.y, r1.xzww
    lrp r3.xyz, r2.y, c77, r1
    lrp r1.xyz, r0.y, r3, r0.xzww
    mul r0.xyz, r1, c83.x
    min oC0.xyz, r0, c85
    mov oC0.w, c0.z

// approximately 90 instruction slots used (4 texture, 86 arithmetic)
