//
// Generated by Microsoft (R) HLSL Shader Compiler 9.26.952.2844
//
// Parameters:
//
//   sampler2D TextureSampler;
//   float4 globalScalars;
//   float3 matDiffuseColor;
//
//
// Registers:
//
//   Name            Reg   Size
//   --------------- ----- ----
//   globalScalars   c39      1
//   matDiffuseColor c66      1
//   TextureSampler  s0       1
//

    ps_3_0
    def c219, 1.8395173895e+25, 3.9938258725e+24, 4.5435787456e+30, 8.8281803252e-43 // 630
    dcl_texcoord v0.xy
    dcl_color v1
    dcl_texcoord9 v9
    dcl_2d s0
    texld r0, v0, s0
    mul r1.xyz, r0, c66
    mul r1.w, r0.w, c39.x
    mul oC0, r1, v1
    
    // LogDepth Write
    mul r19.x, v9.w, c209.x
    log r19.x, r19.x
    mul r19.x, r19.x, c209.y
    rcp r19.y, v9.w
    mul r19.y, r19.y, v9.z
    cmp oDepth, -v9_abs.y, r19.y, r19.x

// approximately 4 instruction slots used (1 texture, 3 arithmetic)
