//
// Generated by Microsoft (R) HLSL Shader Compiler 9.26.952.2844
//
// Parameters:
//
//   sampler2D DirtSampler;
//   float3 LuminanceConstants;
//   sampler2D SpecSampler;
//   sampler2D TextureSampler;
//   sampler2D TextureSampler2;
//   float3 dirtColor;
//   float dirtLevel;
//   float4 gDepthFxParams;
//   float4 gDirectionalColour;
//   float4 gDirectionalLight;
//   float4 gFacetCentre;
//   float4 gLightAmbient0;
//   float4 gLightAmbient1;
//   float4 gLightColB;
//   float4 gLightColG;
//   float4 gLightColR;
//   float4 gLightConeOffset;
//   float4 gLightConeOffset2;
//   float4 gLightConeScale;
//   float4 gLightConeScale2;
//   float4 gLightDir2X;
//   float4 gLightDir2Y;
//   float4 gLightDir2Z;
//   float4 gLightDirX;
//   float4 gLightDirY;
//   float4 gLightDirZ;
//   float4 gLightFallOff;
//   float4 gLightPointColB;
//   float4 gLightPointColG;
//   float4 gLightPointColR;
//   float4 gLightPointFallOff;
//   float4 gLightPointPosX;
//   float4 gLightPointPosY;
//   float4 gLightPointPosZ;
//   float4 gLightPosX;
//   float4 gLightPosY;
//   float4 gLightPosZ;
//   row_major float4x4 gShadowMatrix;
//   float4 gShadowParam0123;
//   float4 gShadowParam14151617;
//   float4 gShadowParam18192021;
//   float4 gShadowParam4567;
//   float4 gShadowParam891113;
//   sampler2D gShadowZSamplerDir;
//   row_major float4x4 gViewInverse;
//   float4 globalFogColor;
//   float4 globalFogColorN;
//   float4 globalFogParams;
//   float4 globalScalars;
//   float3 matDiffuseColor;
//   float4 matDiffuseColor2;
//   float reflectivePowerED;
//   float3 specMapIntMask;
//
//
// Registers:
//
//   Name                 Reg   Size
//   -------------------- ----- ----
//   gViewInverse         c12      4
//   gDepthFxParams       c16      1
//   gDirectionalLight    c17      1
//   gDirectionalColour   c18      1
//   gLightPosX           c19      1
//   gLightPosY           c20      1
//   gLightPosZ           c21      1
//   gLightDirX           c22      1
//   gLightDirY           c23      1
//   gLightDirZ           c24      1
//   gLightFallOff        c25      1
//   gLightConeScale      c26      1
//   gLightConeOffset     c27      1
//   gLightColR           c29      1
//   gLightColG           c30      1
//   gLightColB           c31      1
//   gLightPointPosX      c32      1
//   gLightPointPosY      c33      1
//   gLightPointPosZ      c34      1
//   gLightPointColR      c35      1
//   gLightPointFallOff   c36      1
//   gLightAmbient0       c37      1
//   gLightAmbient1       c38      1
//   globalScalars        c39      1
//   globalFogParams      c41      1
//   globalFogColor       c42      1
//   globalFogColorN      c43      1
//   gShadowParam18192021 c53      1
//   gFacetCentre         c54      1
//   gShadowParam14151617 c56      1
//   gShadowParam0123     c57      1
//   gShadowParam4567     c58      1
//   gShadowParam891113   c59      1
//   gShadowMatrix        c60      4
//   gLightPointColG      c64      1
//   gLightPointColB      c65      1
//   matDiffuseColor      c66      1
//   gLightDir2X          c67      1
//   gLightDir2Y          c68      1
//   gLightDir2Z          c69      1
//   gLightConeScale2     c70      1
//   gLightConeOffset2    c71      1
//   matDiffuseColor2     c72      1
//   dirtLevel            c73      1
//   dirtColor            c74      1
//   specMapIntMask       c75      1
//   reflectivePowerED    c76      1
//   LuminanceConstants   c77      1
//   TextureSampler       s0       1
//   TextureSampler2      s1       1
//   DirtSampler          s2       1
//   SpecSampler          s4       1
//   gShadowZSamplerDir   s15      1
//

    ps_3_0
    def c0, -0.25, 1.33333337, 9.99999975e-005, 190
    def c1, 9.99999975e-006, 47.5, 0.150000006, 0
    def c2, 1, 0, -0.5, 0.5
    def c3, 1.5, -0.326211989, -0.405809999, 0.0833333358
    def c4, -0.791558981, -0.597710013, -0.100000001, 1.11111116
    def c5, 0.212500006, 0.715399981, 0.0720999986, 1.00000001e-007
    def c6, 1, -1, 0, -0
    def c7, 0.896420002, 0.412458003, -0.321940005, -0.932614982
    def c8, 0.185461, -0.893123984, 0.507430971, 0.0644249991
    def c9, 0.473434001, -0.480026007, 0.519456029, 0.767022014
    def c10, -0.203345001, 0.620715976, 0.962339997, -0.194983006
    def c11, -0.840143979, -0.0735799968, -0.69591397, 0.457136989
    dcl_texcoord v0
    dcl_texcoord1 v1
    dcl_texcoord3 v2.xyz
    dcl_color v3
    dcl_texcoord2 v4.xyz
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    dcl_2d s4
    dcl_2d s15
    texld r0, v0, s0
    texld r1, v0.zwzw, s1
    add r2.xyz, c1.x, v1
    nrm r3.xyz, r2
    texld r2, v0, s4
    mul r2.w, r2.w, c76.x
    mul r3.w, r2.w, c1.y
    dp3 r2.x, r2, c75
    mul r2.x, r2.x, c76.x
    mul r2.x, r2.x, c1.z
    mul r4.xyz, r0, c66
    mul r1, r1, c72
    lrp r0.xyz, r1.w, r1, r4
    mul r0, r0, v3
    dp3 r1.x, v3, c77
    mul r1.x, r1.x, c39.z
    mov r1.w, c1.w
    if_lt -c73.x, r1.w
      texld r4, v0, s2
      mul r1.y, r4.x, c73.x
      mov r5.x, c2.x
      mad r5.x, r4.x, -c73.x, r5.x
      lrp r5.yzw, r1.y, c74.xxyz, r0.xxyz
      mad r6, r0.xxyz, c2.yxxx, c2.xyyy
      cmp r4, -r4.x, r6, r5
      mov r0.xyz, r4.yzww
    else
      mov r4.x, c2.x
    endif
    mul r1.y, r2.x, r4.x
    add r2.xyz, c1.x, v2
    nrm r4.xyz, r2
    mad_sat r1.z, r3.z, c2.z, c2.w
    mov r2.xyz, c38
    mad r2.xyz, r2, r1.z, c37
    dp3 r1.z, -r4, r3
    add r1.z, r1.z, r1.z
    mad r5.xyz, r3, -r1.z, -r4
    mul r6.xyz, c18.w, c18
    dp3 r1.z, r3, -c17
    add r1.z, r1.z, c0.x
    mul_sat r1.z, r1.z, c0.y
    dp3_sat r1.w, -c17, r5
    add r1.w, r1.w, c0.z
    mad r2.w, r2.w, c0.w, c0.z
    pow r4.w, r1.w, r2.w
    mul r7.xyz, c61.xyww, v4.y
    mad r7.xyz, v4.x, c60.xyww, r7
    mad r7.xyz, v4.z, c62.xyww, r7
    add r7.xyz, r7, c63.xyww
    dp3 r1.w, c14, v4
    add r8.xyz, -r1.w, -c54
    cmp r8.yzw, r8.xxyz, c2.x, c2.y
    mov r8.x, c2.x
    dp4 r9.x, r8, c57
    dp4 r9.y, r8, c58
    dp4 r10.x, r8, c59
    dp4 r10.y, r8, c56
    mad r7.xy, r7, r9, r10
    add r8.xyz, c15, -v4
    dp3 r1.w, r8, r8
    rsq r1.w, r1.w
    rcp r1.w, r1.w
    rcp r2.w, c53.w
    mul r2.w, r1.w, r2.w
    mul r2.w, r2.w, r2.w
    mul r2.w, r2.w, c3.x
    mov r8.y, c53.y
    mad r8.xz, r8.y, c3.yyzw, r7.xyyw
    texld r9, r8.xzzw, s15
    add r5.w, r7.z, -r9.x
    cmp r5.w, r5.w, c2.x, c2.y
    mad r8.xz, r8.y, c11.xyyw, r7.xyyw
    texld r9, r8.xzzw, s15
    add r6.w, r7.z, -r9.x
    cmp r6.w, r6.w, c2.x, c2.y
    add r5.w, r5.w, r6.w
    mad r8.xz, r8.y, c11.zyww, r7.xyyw
    texld r9, r8.xzzw, s15
    add r6.w, r7.z, -r9.x
    cmp r6.w, r6.w, c2.x, c2.y
    add r5.w, r5.w, r6.w
    mad r8.xz, r8.y, c10.xyyw, r7.xyyw
    texld r9, r8.xzzw, s15
    add r6.w, r7.z, -r9.x
    cmp r6.w, r6.w, c2.x, c2.y
    add r5.w, r5.w, r6.w
    mad r8.xz, r8.y, c10.zyww, r7.xyyw
    texld r9, r8.xzzw, s15
    add r6.w, r7.z, -r9.x
    cmp r6.w, r6.w, c2.x, c2.y
    add r5.w, r5.w, r6.w
    mad r8.xz, r8.y, c9.xyyw, r7.xyyw
    texld r9, r8.xzzw, s15
    add r6.w, r7.z, -r9.x
    cmp r6.w, r6.w, c2.x, c2.y
    add r5.w, r5.w, r6.w
    mad r8.xz, r8.y, c9.zyww, r7.xyyw
    texld r9, r8.xzzw, s15
    add r6.w, r7.z, -r9.x
    cmp r6.w, r6.w, c2.x, c2.y
    add r5.w, r5.w, r6.w
    mad r8.xz, r8.y, c8.xyyw, r7.xyyw
    texld r9, r8.xzzw, s15
    add r6.w, r7.z, -r9.x
    cmp r6.w, r6.w, c2.x, c2.y
    add r5.w, r5.w, r6.w
    mad r8.xz, r8.y, c8.zyww, r7.xyyw
    texld r9, r8.xzzw, s15
    add r6.w, r7.z, -r9.x
    cmp r6.w, r6.w, c2.x, c2.y
    add r5.w, r5.w, r6.w
    mad r8.xz, r8.y, c7.xyyw, r7.xyyw
    texld r9, r8.xzzw, s15
    add r6.w, r7.z, -r9.x
    cmp r6.w, r6.w, c2.x, c2.y
    add r5.w, r5.w, r6.w
    mad r8.xz, r8.y, c7.zyww, r7.xyyw
    texld r9, r8.xzzw, s15
    add r6.w, r7.z, -r9.x
    cmp r6.w, r6.w, c2.x, c2.y
    add r5.w, r5.w, r6.w
    mad r7.xy, r8.y, c4, r7
    texld r8, r7, s15
    add r6.w, r7.z, -r8.x
    cmp r6.w, r6.w, c2.x, c2.y
    add r5.w, r5.w, r6.w
    mad r2.w, r5.w, c3.w, r2.w
    add r1.w, r1.w, -c53.w
    cmp r7.xy, r1.w, c6, c6.zwzw
    add r1.w, r2.w, r7.y
    cmp_sat r1.w, r1.w, r2.w, r7.x
    mul r7.xyz, r6, r4.w
    mul r7.xyz, r1.w, r7
    mul r6.xyz, r6, r1.z
    mul r6.xyz, r1.w, r6
    mad r1.xzw, r2.xyyz, r1.x, r6.xyyz
    add r2, c19, -v4.x
    add r6, c20, -v4.y
    add r8, c21, -v4.z
    mul r9, r2, r2
    mad r9, r6, r6, r9
    mad r9, r8, r8, r9
    add r10, r9, c1.x
    rsq r11.x, r10.x
    rsq r11.y, r10.y
    rsq r11.z, r10.z
    rsq r11.w, r10.w
    mov r10.x, c2.x
    mad r9, r9, -c25, r10.x
    max r12, r9, c1.w
    mul r9, r12, r12
    mad r9, r9, r9, c4.z
    mul r12, r9, c4.w
    cmp r9, r9, r12, c1.w
    mul r12, r3.x, r2
    mad r12, r6, r3.y, r12
    mad r12, r8, r3.z, r12
    mul r9, r9, r12
    mul_sat r9, r11, r9
    mul r12, r2, -c22
    mad r12, r6, -c23, r12
    mad r12, r8, -c24, r12
    mul r12, r11, r12
    mov r13, c26
    mad_sat r12, r12, r13, c27
    mul r9, r9, r12
    mul r2, r5.x, r2
    mad r2, r5.y, r6, r2
    mad r2, r5.z, r8, r2
    mul r2, r11, r2
    log r6.x, r2_abs.x
    log r6.y, r2_abs.y
    log r6.z, r2_abs.z
    log r6.w, r2_abs.w
    mul r2, r3.w, r6
    exp r6.x, r2.x
    exp r6.y, r2.y
    exp r6.z, r2.z
    exp r6.w, r2.w
    mul r2, r9, r6
    dp4 r6.x, c29, r9
    dp4 r6.y, c30, r9
    dp4 r6.z, c31, r9
    dp4 r8.x, c29, r2
    dp4 r8.y, c30, r2
    dp4 r8.z, c31, r2
    add r1.xzw, r1, r6.xyyz
    mad r2.xyz, r7, c17.w, r8
    add r6, c32, -v4.x
    add r7, c33, -v4.y
    add r8, c34, -v4.z
    mul r9, r6, r6
    mad r9, r7, r7, r9
    mad r9, r8, r8, r9
    add r11, r9, c1.x
    rsq r12.x, r11.x
    rsq r12.y, r11.y
    rsq r12.z, r11.z
    rsq r12.w, r11.w
    mad r9, r9, -c36, r10.x
    max r11, r9, c1.w
    mul r9, r11, r11
    mad r9, r9, r9, c4.z
    mul r11, r9, c4.w
    cmp r9, r9, r11, c1.w
    mul r11, r3.x, r6
    mad r11, r7, r3.y, r11
    mad r11, r8, r3.z, r11
    mul r9, r9, r11
    mul_sat r9, r12, r9
    mul r11, r6, -c67
    mad r11, r7, -c68, r11
    mad r11, r8, -c69, r11
    mul r11, r12, r11
    mov r13, c70
    mad_sat r11, r11, r13, c71
    mul r9, r9, r11
    mul r6, r5.x, r6
    mad r6, r5.y, r7, r6
    mad r5, r5.z, r8, r6
    mul r5, r12, r5
    log r6.x, r5_abs.x
    log r6.y, r5_abs.y
    log r6.z, r5_abs.z
    log r6.w, r5_abs.w
    mul r5, r3.w, r6
    exp r6.x, r5.x
    exp r6.y, r5.y
    exp r6.z, r5.z
    exp r6.w, r5.w
    mul r5, r9, r6
    dp4 r6.x, c35, r9
    dp4 r6.y, c64, r9
    dp4 r6.z, c65, r9
    dp4 r7.x, c35, r5
    dp4 r7.y, c64, r5
    dp4 r7.z, c65, r5
    add r5.xyz, r1.xzww, r6
    add r1.xzw, r2.xyyz, r7.xyyz
    dp3 r2.x, r4, r3
    add r2.x, -r2_abs.x, c2.x
    mul r2.x, r2.x, r2.x
    mul r2.x, r2.x, r2.x
    mad_sat r2.x, r2.x, c2.w, c2.w
    mul r1.y, r1.y, r2.x
    mov r5.w, c2.x
    mul r0, r0, r5
    mad r0.xyz, r1.y, r1.xzww, r0
    mul oC0.w, r0.w, c39.x
    add r0.w, c16.w, -v1.w
    add r1.x, -c16.z, c16.w
    rcp r1.x, r1.x
    mul_sat r0.w, r0.w, r1.x
    add r0.w, -r0.w, c2.x
    add r1.xy, -r10.x, c16
    mul r1.y, r0.w, r1.y
    mad r0.w, r0.w, r1.x, c2.x
    dp3 r1.x, r0, c5
    lrp r2.xyz, r0.w, r0, r1.x
    add r0.x, r1.x, c5.w
    pow r2.w, r0_abs.x, r1.y
    mul r0.xyz, r2, r2.w
    rcp r0.w, c41.x
    mul_sat r0.w, r0.w, v1.w
    add r1.x, -c41.x, v1.w
    add r1.y, -c41.x, c41.y
    rcp r1.y, r1.y
    mul_sat r1.x, r1.x, r1.y
    lrp r3.x, c41.w, r0.w, r1.x
    add r0.w, r3.x, c41.z
    mov r3.xyz, c43
    add r1.yzw, -r3.xxyz, c42.xxyz
    mad r1.xyz, r1.x, r1.yzww, c43
    mad r1.xyz, r2, -r2.w, r1
    mad oC0.xyz, r0.w, r1, r0

// approximately 286 instruction slots used (16 texture, 270 arithmetic)
 