//
// Generated by Microsoft (R) HLSL Shader Compiler 9.26.952.2844
//
// Parameters:
//
//   float4 stencil;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   stencil      c52      1
//

    ps_3_0
    def c219, 1.8395173895e+25, 3.9938258725e+24, 4.5435787456e+30, 3.8535707769e-43 // 275
    def c0, 0, 0.00392156886, 1, 0
    dcl_texcoord9 v9
    mov oC0, c0.xxxy
    mov oC1, c0.x
    mov oC2, c0.x
    mov r0.xz, c0
    mul oC3, r0.zxxx, c52.x
    
    // LogDepth Write
    mul r19.x, v9.w, c209.x
    log r19.x, r19.x
    mul r19.x, r19.x, c209.y
    rcp r19.y, v9.w
    mul r19.y, r19.y, v9.z
    cmp oDepth, -v9_abs.y, r19.y, r19.x

// approximately 5 instruction slots used
