// Summary: fixed pop-in/added stippled transparency + stipple mask + alpha toggle + sped up fading for procobj
// Generated by Microsoft (R) HLSL Shader Compiler 9.26.952.2844
//
// Parameters:
//
//   sampler2D TextureSampler;
//   float4 globalScalars;
//   float4 stencil;
//   float4 shadowmap_res;
//
//
// Registers:
//
//   Name           Reg   Size
//   -------------- ----- ----
//   globalScalars  c39      1
//   stencil        c52      1
//   shadowmap_res  c207     1
//   TextureSampler s0       1
//

    ps_3_0
    def c219, 1.8395173895e+25, 3.9938258725e+24, 4.5435787456e+30, 2.1019476965e-43 // 150
    def c152, 0.2, 0.4, 0.6, 0.8 // c152-c154 = new stipple constants
    def c153, 0.5, 2, 1, 0
    def c154, 1.6, 0, 0, 0
    def c0, 0.176470593, -1, -0, 9.99999975e-006
    def c1, 0.5, 0, 1, 0.25
    def c2, 0.3125, 12, 9, 0
    dcl_texcoord v0.xy
    dcl_texcoord1 v1.xyz
    dcl_color v2.xw
    dcl_texcoord9 v9
    dcl vPos.xy
    dcl_2d s0
    texld r0, v0, s0
    mul_sat r0.w, r0.w, c154.x
    // mul r0.w, r0.w, v2.w disabled vertex alpha
    add r20.x, r0.w, -c2.x
    cmp r20.x, r20.x, -c0.y, c0.z
    cmp r0.w, -c223_abs.z, r0.w, r20.x
    mov r20.x, c39.x
    mad_sat r20.y, r20.x, c2.y, -c2.z
    cmp r20.x, -c207_abs.x, r20.y, r20.x
    mul r1.x, r0.w, r20.x
    mov r2.xyz, c0
    mul r20.xy, vPos.xy, c153.x
    frc r20.xy, r20.xy
    mad r20, r20.xxyy, -c153.y, c153.zwzw
    mul r20, r20.xxyy, r20.zwzw
    dp4 r20.x, r20_abs, c152.xzwy
    add r20.y, -r20.x, r1.x
    texkill r20.y
    add r1.yzw, c0.w, v1.xxyz
    dp3 r0.w, r1.yzww, r1.yzww
    rsq r0.w, r0.w
    mad r1.yzw, r1, r0.w, -c0.y
    mul oC1.xyz, r1.yzww, c1.x
    mov oC0.xyz, r0
    mov oC0.w, r1.x
    mov oC1.w, r1.x
    mad oC2.xyz, v2.x, c1.yyzw, c1.ywyw
    // mov oC2.w, r1.x
    add r20.x, -c152.w, r1.x
    cmp oC2.w, r20.x, c0.z, -c0.y
    mul oC3, -r2.yzzz, c52.x
    
    // LogDepth Write
    mul r19.x, v9.w, c209.x
    log r19.x, r19.x
    mul r19.x, r19.x, c209.y
    rcp r19.y, v9.w
    mul r19.y, r19.y, v9.z
    cmp oDepth, -v9_abs.y, r19.y, r19.x

// approximately 18 instruction slots used (1 texture, 17 arithmetic)
