// Summary: added snow texture toggle
// Generated by Microsoft (R) HLSL Shader Compiler 9.26.952.2844
//
// Parameters:
//
//   sampler2D DiffuseTexSampler;
//   sampler2D TextureSampler;
//   float gInvColorExpBias;
//
//
// Registers:
//
//   Name              Reg   Size
//   ----------------- ----- ----
//   gInvColorExpBias  c46      1
//   DiffuseTexSampler s0       1
//   TextureSampler    s1       1
//

    ps_3_0
    def c219, 1.8395173895e+25, 3.9938258725e+24, 4.5435787456e+30, 7.5109597688e-43 // 536
    def c0, 0, 1, 10, 0
    dcl_color v0
    dcl_texcoord v1.xy
    dcl_texcoord9 v9
    dcl_2d s0
    dcl_2d s1
    add r0.xy, c0.zxzw, v1
    texld r0, r0, s0
    mul r0, r0, v0
    mov r1.xy, c0
    mad r1, c46.x, r1.xxxy, r1.yyyx
    mul r0, r0, r1
    texld r2, v1, s1
    cmp r2.w, -c221_abs.y, r2.w, r2.y
    mov r2.xyz, c0.y
    mul r2, r2, v0
    mul r1, r1, r2
    cmp oC0, v1.x, r1, r0
    
    // LogDepth Write
    mul r19.x, v9.w, c209.x
    log r19.x, r19.x
    mul r19.x, r19.x, c209.y
    rcp r19.y, v9.w
    mul r19.y, r19.y, v9.z
    cmp oDepth, -v9_abs.y, r19.y, r19.x

// approximately 10 instruction slots used (2 texture, 8 arithmetic)
