//
// Generated by Microsoft (R) HLSL Shader Compiler 9.26.952.2844
//
// Parameters:
//
//   sampler2D AdapLumSampler;
//   float AdaptTime;
//   float AdaptedLumMax;
//   float AdaptedLumMin;
//   sampler2D CurLumSampler;
//   float ElapsedTime;
//
//
// Registers:
//
//   Name           Reg   Size
//   -------------- ----- ----
//   ElapsedTime    c66      1
//   AdaptTime      c72      1
//   AdaptedLumMin  c73      1
//   AdaptedLumMax  c74      1
//   CurLumSampler  s0       1
//   AdapLumSampler s1       1
//

    ps_3_0
    def c219, 1.8395173895e+25, 3.9938258725e+24, 4.5435787456e+30, 1.1322491592e-42 // 808
    def c0, 0, -1, 1, 0
    dcl_2d s0
    dcl_2d s1
    add r0.x, c72.x, c72.x
    rsq r0.x, r0.x
    mul r0.x, r0.x, c66.x
    min r1.x, r0.x, c0.z
    texld r0, c0.x, s1
    texld r2, c0.x, s0
    lrp r3.x, r1.x, r2.x, r0.x
    max r0.x, r2.x, c73.x
    min r1.x, c74.x, r0.x
    max r0.x, r3.x, c73.x
    min r1.y, c74.x, r0.x
    mov r0.y, c0.y
    add r0.x, r0.y, c72.x
    cmp oC0, r0.x, r1.y, r1.x

// approximately 14 instruction slots used (2 texture, 12 arithmetic)
