// Summary: Scalable bloom + circular toggle
// Generated by Microsoft (R) HLSL Shader Compiler 9.26.952.2844
//
// Parameters:
//
//   sampler2D HDRSampler;
//   float4 TexelSize;
//   float4 globalScreenSize;
//
//
// Registers:
//
//   Name               Reg   Size
//   ------------------ ----- ----
//   globalScreenSize   c44      1
//   TexelSize          c66      1
//   HDRSampler         s0       1
//

    ps_3_0
    def c219, 1.8395173895e+25, 3.9938258725e+24, 4.5435787456e+30, 1.1350517561e-42 // 810
    def c0, 8.503183116e-2, 7.924516248e-2, 7.046251512e-2, 5.977748981e-2
    def c1, 4.838506843e-2, 3.736622266e-2, 2.753221723e-2, 1.935518514e-2
    def c2, 1.298217995e-2, 8.307915518e-3, 5.072600626e-3, 2.955040400e-3
    def c3, 1, 2, 3, 0
    def c4, 4, 5, 6, 0
    def c5, 7, 8, 9, 0
    def c6, 10, 11, 12, 0
    def c7, 0.0018518, 8.7053142952e-2, 0, 0
    dcl_texcoord v0.xy
    dcl_2d s0
    texld r0, v0, s0 // center
    mul r1.xy, c44.yy, c44.zw
    mul r1.xy, r1.xy, c7.x
    mov r2.w, c7.w
    
    if_eq -c218_abs.z, c218_abs.z
      mad r2.xy, r1.xy, c3.xw, v0.xy
      texldl r2.xyz, r2, s0
      add r2.xyz, r2, -r0
      max r2.xyz, r2, c7.w
      mul r3.xyz, r2, c0.x
      mad r2.xy, r1.xy, -c3.xw, v0.xy
      texldl r2.xyz, r2, s0
      add r2.xyz, r2, -r0
      max r2.xyz, r2, c7.w
      mad r3.xyz, r2, c0.x, r3
      mad r2.xy, r1.xy, c3.yw, v0.xy
      texldl r2.xyz, r2, s0
      add r2.xyz, r2, -r0
      max r2.xyz, r2, c7.w
      mad r3.xyz, r2, c0.y, r3
      mad r2.xy, r1.xy, -c3.yw, v0.xy
      texldl r2.xyz, r2, s0
      add r2.xyz, r2, -r0
      max r2.xyz, r2, c7.w
      mad r3.xyz, r2, c0.y, r3
      mad r2.xy, r1.xy, c3.zw, v0.xy
      texldl r2.xyz, r2, s0
      add r2.xyz, r2, -r0
      max r2.xyz, r2, c7.w
      mad r3.xyz, r2, c0.z, r3
      mad r2.xy, r1.xy, -c3.zw, v0.xy
      texldl r2.xyz, r2, s0
      add r2.xyz, r2, -r0
      max r2.xyz, r2, c7.w
      mad r3.xyz, r2, c0.z, r3
      mad r2.xy, r1.xy, c4.xw, v0.xy
      texldl r2.xyz, r2, s0
      add r2.xyz, r2, -r0
      max r2.xyz, r2, c7.w
      mad r3.xyz, r2, c0.w, r3
      mad r2.xy, r1.xy, -c4.xw, v0.xy
      texldl r2.xyz, r2, s0
      add r2.xyz, r2, -r0
      max r2.xyz, r2, c7.w
      mad r3.xyz, r2, c0.w, r3
      
      mad r2.xy, r1.xy, c4.yw, v0.xy
      texldl r2.xyz, r2, s0
      add r2.xyz, r2, -r0
      max r2.xyz, r2, c7.w
      mad r3.xyz, r2, c1.x, r3
      mad r2.xy, r1.xy, -c4.yw, v0.xy
      texldl r2.xyz, r2, s0
      add r2.xyz, r2, -r0
      max r2.xyz, r2, c7.w
      mad r3.xyz, r2, c1.x, r3
      mad r2.xy, r1.xy, c4.zw, v0.xy
      texldl r2.xyz, r2, s0
      add r2.xyz, r2, -r0
      max r2.xyz, r2, c7.w
      mad r3.xyz, r2, c1.y, r3
      mad r2.xy, r1.xy, -c4.zw, v0.xy
      texldl r2.xyz, r2, s0
      add r2.xyz, r2, -r0
      max r2.xyz, r2, c7.w
      mad r3.xyz, r2, c1.y, r3
      mad r2.xy, r1.xy, c5.xw, v0.xy
      texldl r2.xyz, r2, s0
      add r2.xyz, r2, -r0
      max r2.xyz, r2, c7.w
      mad r3.xyz, r2, c1.z, r3
      mad r2.xy, r1.xy, -c5.xw, v0.xy
      texldl r2.xyz, r2, s0
      add r2.xyz, r2, -r0
      max r2.xyz, r2, c7.w
      mad r3.xyz, r2, c1.z, r3
      mad r2.xy, r1.xy, c5.yw, v0.xy
      texldl r2.xyz, r2, s0
      add r2.xyz, r2, -r0
      max r2.xyz, r2, c7.w
      mad r3.xyz, r2, c1.w, r3
      mad r2.xy, r1.xy, -c5.yw, v0.xy
      texldl r2.xyz, r2, s0
      add r2.xyz, r2, -r0
      max r2.xyz, r2, c7.w
      mad r3.xyz, r2, c1.w, r3
      
      mad r2.xy, r1.xy, c5.zw, v0.xy
      texldl r2.xyz, r2, s0
      add r2.xyz, r2, -r0
      max r2.xyz, r2, c7.w
      mad r3.xyz, r2, c2.x, r3
      mad r2.xy, r1.xy, -c5.zw, v0.xy
      texldl r2.xyz, r2, s0
      add r2.xyz, r2, -r0
      max r2.xyz, r2, c7.w
      mad r3.xyz, r2, c2.x, r3
      mad r2.xy, r1.xy, c6.xw, v0.xy
      texldl r2.xyz, r2, s0
      add r2.xyz, r2, -r0
      max r2.xyz, r2, c7.w
      mad r3.xyz, r2, c2.y, r3
      mad r2.xy, r1.xy, -c6.xw, v0.xy
      texldl r2.xyz, r2, s0
      add r2.xyz, r2, -r0
      max r2.xyz, r2, c7.w
      mad r3.xyz, r2, c2.y, r3
      mad r2.xy, r1.xy, c6.yw, v0.xy
      texldl r2.xyz, r2, s0
      add r2.xyz, r2, -r0
      max r2.xyz, r2, c7.w
      mad r3.xyz, r2, c2.z, r3
      mad r2.xy, r1.xy, -c6.yw, v0.xy
      texldl r2.xyz, r2, s0
      add r2.xyz, r2, -r0
      max r2.xyz, r2, c7.w
      mad r3.xyz, r2, c2.z, r3
      mad r2.xy, r1.xy, c6.zw, v0.xy
      texldl r2.xyz, r2, s0
      add r2.xyz, r2, -r0
      max r2.xyz, r2, c7.w
      mad r3.xyz, r2, c2.w, r3
      mad r2.xy, r1.xy, -c6.zw, v0.xy
      texldl r2.xyz, r2, s0
      add r2.xyz, r2, -r0
      max r2.xyz, r2, c7.w
      mad r3.xyz, r2, c2.w, r3
      
      add oC0.xyz, r3, r0
    else
      mad r2.xy, r1.xy, c3.xw, v0.xy
      texldl r2.xyz, r2, s0
      mul r3.xyz, r2, c0.x
      mad r2.xy, r1.xy, -c3.xw, v0.xy
      texldl r2.xyz, r2, s0
      mad r3.xyz, r2, c0.x, r3
      mad r2.xy, r1.xy, c3.yw, v0.xy
      texldl r2.xyz, r2, s0
      mad r3.xyz, r2, c0.y, r3
      mad r2.xy, r1.xy, -c3.yw, v0.xy
      texldl r2.xyz, r2, s0
      mad r3.xyz, r2, c0.y, r3
      mad r2.xy, r1.xy, c3.zw, v0.xy
      texldl r2.xyz, r2, s0
      mad r3.xyz, r2, c0.z, r3
      mad r2.xy, r1.xy, -c3.zw, v0.xy
      texldl r2.xyz, r2, s0
      mad r3.xyz, r2, c0.z, r3
      mad r2.xy, r1.xy, c4.xw, v0.xy
      texldl r2.xyz, r2, s0
      mad r3.xyz, r2, c0.w, r3
      mad r2.xy, r1.xy, -c4.xw, v0.xy
      texldl r2.xyz, r2, s0
      mad r3.xyz, r2, c0.w, r3
      
      mad r2.xy, r1.xy, c4.yw, v0.xy
      texldl r2.xyz, r2, s0
      mad r3.xyz, r2, c1.x, r3
      mad r2.xy, r1.xy, -c4.yw, v0.xy
      texldl r2.xyz, r2, s0
      mad r3.xyz, r2, c1.x, r3
      mad r2.xy, r1.xy, c4.zw, v0.xy
      texldl r2.xyz, r2, s0
      mad r3.xyz, r2, c1.y, r3
      mad r2.xy, r1.xy, -c4.zw, v0.xy
      texldl r2.xyz, r2, s0
      mad r3.xyz, r2, c1.y, r3
      mad r2.xy, r1.xy, c5.xw, v0.xy
      texldl r2.xyz, r2, s0
      mad r3.xyz, r2, c1.z, r3
      mad r2.xy, r1.xy, -c5.xw, v0.xy
      texldl r2.xyz, r2, s0
      mad r3.xyz, r2, c1.z, r3
      mad r2.xy, r1.xy, c5.yw, v0.xy
      texldl r2.xyz, r2, s0
      mad r3.xyz, r2, c1.w, r3
      mad r2.xy, r1.xy, -c5.yw, v0.xy
      texldl r2.xyz, r2, s0
      mad r3.xyz, r2, c1.w, r3
      
      mad r2.xy, r1.xy, c5.zw, v0.xy
      texldl r2.xyz, r2, s0
      mad r3.xyz, r2, c2.x, r3
      mad r2.xy, r1.xy, -c5.zw, v0.xy
      texldl r2.xyz, r2, s0
      mad r3.xyz, r2, c2.x, r3
      mad r2.xy, r1.xy, c6.xw, v0.xy
      texldl r2.xyz, r2, s0
      mad r3.xyz, r2, c2.y, r3
      mad r2.xy, r1.xy, -c6.xw, v0.xy
      texldl r2.xyz, r2, s0
      mad r3.xyz, r2, c2.y, r3
      mad r2.xy, r1.xy, c6.yw, v0.xy
      texldl r2.xyz, r2, s0
      mad r3.xyz, r2, c2.z, r3
      mad r2.xy, r1.xy, -c6.yw, v0.xy
      texldl r2.xyz, r2, s0
      mad r3.xyz, r2, c2.z, r3
      mad r2.xy, r1.xy, c6.zw, v0.xy
      texldl r2.xyz, r2, s0
      mad r3.xyz, r2, c2.w, r3
      mad r2.xy, r1.xy, -c6.zw, v0.xy
      texldl r2.xyz, r2, s0
      mad r3.xyz, r2, c2.w, r3
      
      mad oC0.xyz, c7.y, r0, r3
    endif
    mov oC0.w, c7.w

// approximately 40 instruction slots used (7 texture, 33 arithmetic)
