//
// Generated by Microsoft (R) HLSL Shader Compiler 9.26.952.2844
//
// Parameters:
//
//   float3 AzimuthColor;
//   float3 AzimuthColorEast;
//   float AzimuthHeight;
//   float AzimuthStrength;
//   float CloudShadowOffset;
//   float4 CloudThicknessEdgeSmoothDetailScaleStrength;
//   float2 DetailOffset;
//   float2 GalaxyOffset;
//   float3 SkyColor;
//   float StarFieldUVRepeat;
//   float4 SunDirection;
//   float4 TopCloudBiasDetailThresholdHeight;
//   float dpMapFarClip;
//   row_major float4x4 gWorld;
//   row_major float4x4 gWorldViewProj;
//
//
// Registers:
//
//   Name                                        Reg   Size
//   ------------------------------------------- ----- ----
//   gWorld                                      c0       4
//   gWorldViewProj                              c8       4
//   SunDirection                                c64      1
//   SkyColor                                    c65      1
//   AzimuthColor                                c66      1
//   AzimuthColorEast                            c67      1
//   AzimuthHeight                               c68      1
//   TopCloudBiasDetailThresholdHeight           c69      1
//   CloudShadowOffset                           c70      1
//   AzimuthStrength                             c71      1
//   CloudThicknessEdgeSmoothDetailScaleStrength c72      1
//   StarFieldUVRepeat                           c73      1
//   GalaxyOffset                                c74      1
//   DetailOffset                                c75      1
//   dpMapFarClip                                c76      1
//

    vs_3_0
    def c230, 1.8395173895e+25, 3.9938258725e+24, 4.5435787456e+30, 2.8460371810e-42 // 2031
    def c4, -0.0187292993, 0.0742610022, -0.212114394, 1.57072878
    def c5, -2, 3.14159274, 1.57079637, 0.317732662
    def c6, 0.5, 0.100000001, 2, -1
    def c7, 1, 9.99999975e-006, 1.5, 0.500010014
    def c12, -0.5, -0.499989986, -1, -0
    dcl_position v0
    dcl_texcoord v1
    dcl_position o0
    dcl_texcoord o1.xyz
    dcl_texcoord1 o2.xyz
    dcl_texcoord2 o3
    dcl_texcoord3 o4
    dcl_texcoord4 o5.xyz
    dcl_texcoord5 o6.xyz
    mul r0.xyz, c1, v0.y
    mad r0.xyz, v0.x, c0, r0
    mad r0.xyz, v0.z, c2, r0
    mad r0.xyz, v0.w, c3, r0
    add r0.xyz, r0, -c3
    add r1.xyz, r0, c7.y
    mov o2.xyz, r0
    dp3 r0.x, r1, r1
    rsq r0.x, r0.x
    mul r2.xyz, r1, r0.x
    mad r0.xy, r1.xzzw, -r0.x, c64.xzzw
    mul r2.w, r2.y, c7.z
    add r1.xyz, r2.xwzw, c7.ywyw
    dp3 r0.z, r1, r1
    rsq r0.z, r0.z
    mul r0.zw, r1.xyxz, r0.z
    mad r1.xy, r0_abs.zwzw, c4.x, c4.y
    mad r1.xy, r1, r0_abs.zwzw, c4.z
    mad r1.xy, r1, r0_abs.zwzw, c4.w
    add r1.zw, -r0_abs, c7.x
    slt r0.zw, r0, -r0
    rsq r1.z, r1.z
    rsq r1.w, r1.w
    rcp r1.w, r1.w
    mul r1.y, r1.y, r1.w
    rcp r1.z, r1.z
    mul r1.x, r1.x, r1.z
    mad r1.z, r1.x, c5.x, c5.y
    mad r0.z, r1.z, r0.z, r1.x
    add r0.z, -r0.z, c5.z
    mov r1.w, c5.w
    mad r2.z, r0.z, r1.w, c74.x
    mad r0.z, r1.y, c5.x, c5.y
    mad r0.z, r0.z, r0.w, r1.y
    add r0.z, -r0.z, c5.z
    mad r2.w, r0.z, r1.w, c74.y
    add r0.zw, r2, c6.x
    mul o4.xy, r0.zwzw, c73.x
    mov o4.zw, r0
    mov r1.xy, c6
    mul r0.z, r1.y, c70.x
    mul r0.xy, r0, r0.z
    mad r0.zw, v1.xyxy, c6.z, c6.w
    mul r0.zw, r0, r0
    add r0.z, r0.w, r0.z
    add r0.z, -r0.z, c7.x
    mad o3.xy, r0, r0.z, v1
    add r0, c12.xxyy, v1.xyxy
    mul r3, r0, r0
    add r1.yz, r3.xyww, r3.xxzw
    rsq r1.z, r1.z
    mul r0.zw, r0, r1.z
    mul r0.zw, r1.y, r0
    mov r1.z, c72.z
    mad o3.zw, r0, r1.z, c75.xyxy
    mul r0.zw, r0.xyxy, c69.w
    mad o5.xy, r0, c69.w, r1.x
    mul r0.xy, r0.zwzw, r0.zwzw
    add r0.x, r0.y, r0.x
    rsq r0.x, r0.x
    rcp r0.x, r0.x
    add o5.z, -r0.x, c7.x
    mul r0, c9, v0.y
    mad r0, v0.x, c8, r0
    mad r0, v0.z, c10, r0
    add r0, r0, c11
    rcp r1.x, c76.x
    mad o1.z, r0.z, -r1.x, c7.x
    mul r1.x, r0.z, r1.x
    mul_sat r1.x, r2.y, c68.x
    mad r1.y, r2.x, c6.x, c6.x
    add r1.x, -r1.x, c7.x
    mul r1.x, r1.x, c71.x
    mov r2.xyz, c67
    add r2.xyz, -r2, c66
    mad r1.yzw, r1.y, r2.xxyz, c67.xxyz
    mad o6.xyz, r1.yzww, r1.x, c65
    rcp r0.w, r0_abs.w
    mul r0.xyz, r0, r0.w
    dp3 r0.w, r0, r0
    rsq r0.w, r0.w
    mad r0.z, r0.z, r0.w, c7.x
    mul r0.xy, r0, r0.w
    rcp r0.z, r0.z
    mul r0.xyz, r0.xyxw, r0.z
    mad r0.xyw, r0.xyzz, -c12.xzzw, -c12.xwzz
    mov o0, r0.xyww // LogDepth Write - Sky
    mov o1.xy, v1

// approximately 88 instruction slots used
