//
// Generated by Microsoft (R) HLSL Shader Compiler 9.26.952.2844
    ps_3_0
    def c219, 1.8395173895e+25, 3.9938258725e+24, 4.5435787456e+30, 4.3440252394e-44 // 31
    def c0, 1, 0, 0, 0
    dcl_texcoord v0.xyz
    dcl_texcoord9 v9
    mad oC0, v0.xyzx, c0.xxxy, c0.yyyx
    
    // LogDepth Write
    mul r19.x, v9.w, c209.x
    log r19.x, r19.x
    mul r19.x, r19.x, c209.y
    rcp r19.y, v9.w
    mul r19.y, r19.y, v9.z
    cmp oDepth, -v9_abs.y, r19.y, r19.x

// approximately 1 instruction slot used
